# Generated by Django 3.1.7 on 2021-04-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeskTop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100)),
                ('Price', models.IntegerField(default=20000)),
                ('status', models.CharField(choices=[('Available', 'Stock is available'), ('Sold', 'Stocks  are soldout'), ('Restocking', 'Restoking currently')], default='Available', max_length=200)),
                ('issues', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100)),
                ('Price', models.IntegerField(default=20000)),
                ('status', models.CharField(choices=[('Available', 'Stock is available'), ('Sold', 'Stocks  are soldout'), ('Restocking', 'Restoking currently')], default='Available', max_length=200)),
                ('issues', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100)),
                ('Price', models.IntegerField(default=20000)),
                ('status', models.CharField(choices=[('Available', 'Stock is available'), ('Sold', 'Stocks  are soldout'), ('Restocking', 'Restoking currently')], default='Available', max_length=200)),
                ('issues', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
